//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architecture.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_sv {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_sv() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Architecture.Resources.Strings.sv", typeof(Strings_sv).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string GenErr_CheckYourNetworkMessage {
            get {
                return ResourceManager.GetString("GenErr_CheckYourNetworkMessage", resourceCulture);
            }
        }
        
        internal static string GenErr_NoNetworkMessage {
            get {
                return ResourceManager.GetString("GenErr_NoNetworkMessage", resourceCulture);
            }
        }
        
        internal static string GenErr_NoNetworkTitle {
            get {
                return ResourceManager.GetString("GenErr_NoNetworkTitle", resourceCulture);
            }
        }
        
        internal static string Gen_Cancel {
            get {
                return ResourceManager.GetString("Gen_Cancel", resourceCulture);
            }
        }
        
        internal static string Gen_Close {
            get {
                return ResourceManager.GetString("Gen_Close", resourceCulture);
            }
        }
        
        internal static string Gen_Loading {
            get {
                return ResourceManager.GetString("Gen_Loading", resourceCulture);
            }
        }
        
        internal static string Gen_Login {
            get {
                return ResourceManager.GetString("Gen_Login", resourceCulture);
            }
        }
        
        internal static string Gen_Mail {
            get {
                return ResourceManager.GetString("Gen_Mail", resourceCulture);
            }
        }
        
        internal static string Gen_Map {
            get {
                return ResourceManager.GetString("Gen_Map", resourceCulture);
            }
        }
        
        internal static string Gen_No {
            get {
                return ResourceManager.GetString("Gen_No", resourceCulture);
            }
        }
        
        internal static string Gen_Password {
            get {
                return ResourceManager.GetString("Gen_Password", resourceCulture);
            }
        }
        
        internal static string Gen_Password_Confirm {
            get {
                return ResourceManager.GetString("Gen_Password_Confirm", resourceCulture);
            }
        }
        
        internal static string Gen_RememberMe {
            get {
                return ResourceManager.GetString("Gen_RememberMe", resourceCulture);
            }
        }
        
        internal static string Gen_Restart {
            get {
                return ResourceManager.GetString("Gen_Restart", resourceCulture);
            }
        }
        
        internal static string Gen_Sign_Up {
            get {
                return ResourceManager.GetString("Gen_Sign_Up", resourceCulture);
            }
        }
        
        internal static string Gen_Username {
            get {
                return ResourceManager.GetString("Gen_Username", resourceCulture);
            }
        }
        
        internal static string Gen_Yes {
            get {
                return ResourceManager.GetString("Gen_Yes", resourceCulture);
            }
        }
        
        internal static string Login_In_Process {
            get {
                return ResourceManager.GetString("Login_In_Process", resourceCulture);
            }
        }
        
        internal static string Missing_Mail {
            get {
                return ResourceManager.GetString("Missing_Mail", resourceCulture);
            }
        }
        
        internal static string Missing_Password {
            get {
                return ResourceManager.GetString("Missing_Password", resourceCulture);
            }
        }
        
        internal static string Missing_Username {
            get {
                return ResourceManager.GetString("Missing_Username", resourceCulture);
            }
        }
        
        internal static string Permission_Message {
            get {
                return ResourceManager.GetString("Permission_Message", resourceCulture);
            }
        }
        
        internal static string Permission_Settings {
            get {
                return ResourceManager.GetString("Permission_Settings", resourceCulture);
            }
        }
        
        internal static string Permission_Title {
            get {
                return ResourceManager.GetString("Permission_Title", resourceCulture);
            }
        }
        
        internal static string Sign_Up {
            get {
                return ResourceManager.GetString("Sign_Up", resourceCulture);
            }
        }
        
        internal static string Forgot_Password {
            get {
                return ResourceManager.GetString("Forgot_Password", resourceCulture);
            }
        }
        
        internal static string Gen_Or {
            get {
                return ResourceManager.GetString("Gen_Or", resourceCulture);
            }
        }
    }
}
